name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - LeoWorking

jobs:
  deploy:
    name: Deploy to EC2 on LeoWorking branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY}}
          REMOTE_HOST: ${{ secrets.HOST}}
          REMOTE_USER: ${{ secrets.USERNAME}}
          TARGET: ${{ secrets.TARGET}}